### ISSUE TITLE
feat: parameters for whats new page

### ISSUE THREAD

**Issue by flowwishthebest** [flowwishthebest/stay-productive-landing#3]
Add two query parameters for route GET /whats-new called `from` to `to`.
They describe versions of "stay-productive" extension.
Allowed values are `x.x` format, where `x` is a positive integer.
Do not use any vendor's libs.

**Comment by TDP17** [comment]
Hi! I would like to try my hand at this for hacktober 😄 

Few things I would like to get cleared 
You want me to add 2 query params named **from** and **to** respectively on the get route and validate them

- What behavior is expected if the params are not validated, that is they do not match the allowed format (400, bad request page?)
- What do you want me to do with the params in the get request? Should I just display them on the screen for the moment?

**Comment by flowwishthebest** [comment]
Hi!
Thank you for your interest. I'm sorry for late answer.

1. I think you need to do nothing in this case, just send it back to client. I will show general or last updates page of extension in future;
2. Yes, just send it to client as string with format like `Whats new from x to x`.

--
Ilya

**Comment by flowwishthebest** [comment]
Thanks!
